name: PCA_slider
channels:
  - conda-forge
  - daytum
  - defaults
dependencies:
  - aiohttp=3.5.4
  - appdirs=1.4.3
  - appnope=0.1.0
  - arrow-cpp=0.14.0
  - asn1crypto=0.24.0
  - async-timeout=3.0.1
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bokeh=1.2.0
  - boost-cpp=1.70.0
  - brotli=1.0.7
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.1
  - cryptography=2.7
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=2.1.0
  - dask-core=2.1.0
  - data=0.0.33
  - decorator=4.4.0
  - defusedxml=0.5.0
  - distributed=2.1.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - fastparquet=0.3.1
  - freetype=2.10.0
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.22.0
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.8
  - intake=0.5.1
  - intake-parquet=0.2.1
  - intake-sql=0.2.0
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - jedi=0.14.0
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter-server-proxy=1.1.0
  - jupyter_client=5.3.0
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libedit=3.1.20170329
  - libevent=2.1.10
  - libffi=3.2.1
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libpq=11.4
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libtiff=4.0.10
  - llvm-openmp=8.0.0
  - llvmlite=0.29.0
  - locket=0.2.0
  - lz4-c=1.8.3
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.6.1
  - multidict=4.5.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numba=0.44.1
  - numpy=1.16.4
  - olefile=0.46
  - openblas=0.3.6
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - panel=0.6.0
  - param=1.9.1
  - parquet-cpp=1.5.1
  - parso=0.5.0
  - partd=1.0.0
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - psycopg2=2.8.3
  - ptyprocess=0.6.0
  - pyarrow=0.14.0
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyrsistent=0.15.3
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-snappy=0.5.4
  - pytz=2019.1
  - pyviz_comms=0.7.2
  - pyyaml=5.1.1
  - pyzmq=18.0.2
  - re2=2019.07.01
  - readline=8.0
  - requests=2.22.0
  - ruamel=1.0
  - ruamel.yaml=0.15.96
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - simpervisor=0.3
  - six=1.12.0
  - snappy=1.1.7
  - sortedcontainers=2.1.0
  - sqlalchemy=1.3.5
  - sqlite=3.28.0
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.3.1
  - thrift=0.11.0
  - thrift-cpp=0.12.0
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - uriparser=0.9.3
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - webencodings
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zeromq=4.3.1
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.4.0
